GET http://localhost:3003/api/blogs
content-type: application/json

{}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGM3ODcyZTc1MDA5NTIzM2FlNGRmOSIsImlhdCI6MTY2NTk1NTk1OCwiZXhwIjoxNjY2MjE1MTU4fQ.K9hItkCotw3JePJqNpW3kcDD8n7TXDmn-71RY_gM5dA

{
  "title": "New blog title 1",
  "author": "George",
  "url": "www.test.com",
  "likes": "2",
  "userId": "634bd24d3f6681512395ee65"
}

###

DELETE http://localhost:3003/api/blogs/634c7888e750095233ae4dfe
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGM3ODcyZTc1MDA5NTIzM2FlNGRmOSIsImlhdCI6MTY2NTk1NTk1OCwiZXhwIjoxNjY2MjE1MTU4fQ.K9hItkCotw3JePJqNpW3kcDD8n7TXDmn-71RY_gM5dA


###



